# Schema for the configuration files of the iai_pig module.

block.settings.iai_product_image_gallery:
  type: block_settings
  label: 'Product Image Gallery'
  mapping:
    block_count:
      type: integer
      label: 'Block count'
